matrix:
  DOCKER_REPO:
    - ukhomeofficedigital/drone-housekeeping
  DOCKER_REGISTRY:
    - quay.io
  DOCKER_USERNAME:
    - ukhomeofficedigital+drone_housekeeping
  DOCKER_HOST:
    - tcp://172.17.0.1:2375
  HELM_REPO:
    - ukhomeofficedigital/helm-drone-housekeeping
  HELM_REGISTRY:
    - quay.io
  HELM_USERNAME:
    - ukhomeofficedigital+helm_drone_housekeeping

pipeline:
  docker-build:
    image: docker:19.03.12
    commands:
      - docker build -t ${DOCKER_REGISTRY}/${DOCKER_REPO}:$${DRONE_COMMIT_SHA} .
    when:
      event:
        - pull_request
        - push
        - tag

  docker-publish:
    image: docker:19.03.12
    environment:
      docker_username: $DOCKER_USERNAME
    secrets:
      - docker_password
    commands:
      - apk add --no-cache bash
      - ./publish-image.sh
    when:
      event: tag

  docker-latest:
    image: docker:19.03.12
    environment:
      docker_username: $DOCKER_USERNAME
    secrets:
      - docker_password
    commands:
      - docker login -u="${DOCKER_USERNAME}" -p=$${DOCKER_PASSWORD} ${DOCKER_REGISTRY}
      - docker tag ${DOCKER_REGISTRY}/${DOCKER_REPO}:$${DRONE_COMMIT_SHA} ${DOCKER_REGISTRY}/${DOCKER_REPO}:latest
      - docker push ${DOCKER_REGISTRY}/${DOCKER_REPO}:$${DRONE_COMMIT_SHA}
      - docker push ${DOCKER_REGISTRY}/${DOCKER_REPO}:latest
    when:
      event: push
      branch: master

  helm_lint:
    image: quay.io/ukhomeofficedigital/helm:v3.2.4
    commands:
      - cd helm
      - helm lint
    when:
      event: [push, pull_request]

  helm_publish:
    image: quay.io/ukhomeofficedigital/helm:v3.2.4
    environment:
      helm_username: $HELM_USERNAME
    secrets:
      - helm_password
    commands:
      - ./publish-chart.sh
    when:
      event: tag
