apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsNonRoot: true
          containers:
          - name: {{ .Release.Name }}
            image: "{{ .Values.image.name }}:{{ .Values.image.version }}"
            envFrom:
              - secretRef:
                  name: {{ .Release.Name }}
            {{- if .Values.resources }}
            resources:
{{ toYaml .Values.resources | indent 14 }}
            {{- end }}
            {{- if .Values.extraEnv }}
            env:
{{ toYaml .Values.extraEnv | indent 12 }}
            {{- end }}
          restartPolicy: OnFailure
